---
title: "Hacia una propuesta de medición de Cohesión Social con ELSOC"
date: "2021-05-22"
author: ["Castillo, Juan Carlos", "Iturra, Julio", "Carrasco, Kevin"]
publication: ""
abstract: ""
categories: ["Documento de trabajo"]
about:
  template: marquee
format: 
  html: 
   theme: ../../../scss-posts.scss
---

# Introducción 

El objetivo de este informe es responder a un requerimiento que busca identificar los principales indicadores presentes en el Estudio Longitudinal Social de Chile (ELSOC) que permitan operacionalizar y medir el concepto de cohesión social a partir de una revisión sistemática de distintas propuestas y experiencias de estudios internacionales. Para ello, toma como principal referencia el documento de trabajo Conceptos y medición de cohesión social en proyectos internacionales de COES (Castillo et al., 2021). En primer lugar, se generará una sistematización de las principales propuestas de dimensiones, subdimensiones e indicadores bajo los cuales se ha medido cohesión social a nivel internacional, señalando las principales similitudes y diferencias entre cada estudio. En segundo lugar, se analizará en qué medida las principales dimensiones y subdimensiones de cohesión social son posibles de operacionalizar con indicadores presentes en ELSOC. Para ello, se elaborarán dos insumos principales. Por un lado, una planilla que presenta la sistematización general de las dimensiones, subdimensiones e indicadores de ELSOC y la fuente de información desde dónde proviene el planteamiento de medición de la variable y, por otro lado, un documento escrito que sintetiza esta sistematización de dimensiones, subdimensiones e indicadores de manera detallada.

::: {.button}
[Documento completo](https://ocscoes.github.io/cohesion-elsoc/){.btn role="button" style="background-color: #0693e3; color: white; margin-top: 0em;"}
:::